### ISSUE TITLE
Empty Compiled Source

### ISSUE THREAD

**Issue by segg21** [AJS-development/OAPluginCompiler#1]
I'm puzzled why my plugin won't compile, but the sample will. 

The plugin works perfectly, Dev mode. But compiling on the other hand, no.

It took me a while to actually figure out exactly how to compile, found this and face palmed. I thought there was a way within OA to do so, however time time wasted searching it was not.

Plugin provided on gitter, you can also add thoughts to the code aswell.

**Comment by Andrews54757** [comment]
@LegitSoulja This is because you are using "strict mode". Apparently, a module this uses doesnt support it.

**Comment by Andrews54757** [comment]
I will fix for you

**Comment by Andrews54757** [comment]
Also, request is asynchronous. You are trying to use it like if it was synchronous

**Comment by Andrews54757** [comment]
[plugin.zip](https://google.com)

**Comment by segg21** [comment]
@Andrews54757 well, 'use strict' was added because it didn't work, I thought I had some unknown file error. However, that wasn't the issue neither.

The files was changed, so im guessing I can't use normal classes instead of prototypes?

**Comment by segg21** [comment]
@Andrews54757 yea, tested it and it still doesn't work. As of the file js.js(~.js), it says module not found after being compiled and ranned. Since that happened, I figured out your little cache trick :)
